### ISSUE TITLE
Make sections modular

### ISSUE THREAD

**Issue by jacobneu** [txa/cftlfp#4]
It doesn't make sense to keep everything a multi-thousand line tex file. Should be split into standalone files, ideally which can be compiled separately.

**Comment by txa** [comment]
(base) txa@MACBOOK-C02FG06YML88 cftlfp % make
make: *** No rule to make target `sols', needed by `all'.  Stop.

**Comment by txa** [comment]
I think the rule for sold is missing in Makefile.

**Comment by txa** [comment]
Can you also add an empty chapter introduction in the beginning?

**Comment by jacobneu** [comment]
> I think the rule for sols is missing in Makefile.

#10 changes the default behavior to include sols. So the options are `make pdf` (which includes solutions) or `make nosols` (which doesn't)

**Comment by jacobneu** [comment]
> Can you also add an empty chapter introduction in the beginning?

This should be discussed in the pull request: https://github.com/txa/cftlfp/pull/10#issuecomment-2232987413

**Comment by txa** [comment]
If I just type in make I get an error. Is this intended.
